---
- name: Prepare system for web penetration testing
  hosts: all
  become: yes
  vars:
    tools_dir: "/home/kali/Desktop/web_pentest_tools"
  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required tools
      apt:
        name:
          - git
          - curl
          - python3-pip
          - unzip
        state: present

    - name: Create tools directory
      file:
        path: "{{ tools_dir }}"
        state: directory
        mode: '0755'

    - name: Create ffuf directory
      file:
        path: "{{ tools_dir }}/ffuf"
        state: directory
        mode: '0755'

    - name: Download and extract ffuf
      block:
        - name: Download ffuf archive
          get_url:
            url: "https://github.com/ffuf/ffuf/releases/download/v2.1.0/ffuf_2.1.0_linux_amd64.tar.gz"
            dest: "{{ tools_dir }}/ffuf/ffuf.tar.gz"

        - name: Extract ffuf
          unarchive:
            src: "{{ tools_dir }}/ffuf/ffuf.tar.gz"
            dest: "{{ tools_dir }}/ffuf"
            remote_src: yes

    - name: Download wordlists for ffuf
      get_url:
        url: "{{ item.url }}"
        dest: "{{ tools_dir }}/ffuf/{{ item.dest }}"
      loop:
        - { url: "http://ffuf.me/wordlist/common.txt", dest: "common.txt" }
        - { url: "http://ffuf.me/wordlist/parameters.txt", dest: "parameters.txt" }
        - { url: "http://ffuf.me/wordlist/subdomains.txt", dest: "subdomains.txt" }

    - name: Download WhatCMS script
      get_url:
        url: "https://github.com/GONZOsint/WhatCMS/blob/master/whatcms.sh"
        dest: "{{ tools_dir }}/whatcms.sh"
        mode: '0755'

    - name: Download rockyou.txt wordlist
      get_url:
        url: "https://github.com/praetorian-inc/Hob0Rules/raw/master/wordlists/rockyou.txt.gz"
        dest: "{{ tools_dir }}/rockyou.txt.gz"

    - name: Extract rockyou.txt
      command: "gunzip -f {{ tools_dir }}/rockyou.txt.gz"
